[package]
name = "rust_linux_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ls"
path = "commands/ls/src/main.rs"

[[bin]]
name = "cat"
path = "commands/cat/src/main.rs"

[[bin]]
name = "simple_config"
path = "macro/simple_config/src/main.rs"

[workspace]
members = [
    "commands/ls",
    "commands/cat",
    "macro/simple_config"
]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ls = { path = "commands/ls" }
cat = { path = "commands/cat" }
simple_config = { path = "macro/simple_config" }
clap = "3.2.22"
nom = "7.1.1"
chrono = "0.4.19"
colored = "2.0.0"
quote = "1.0.9"
syn = "1.0.76"